// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace rpsls
{
	public partial class ChooseGameNavigationViewController : UINavigationController
	{
		public ChooseGameNavigationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
