// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace rpsls
{
	public partial class ChooseGameViewController : UIViewController
	{
		public ChooseGameViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}
	}
}
