// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace rpsls
{
	public partial class ChooseNickViewController : UIViewController
	{
		public ChooseNickViewController (IntPtr handle) : base (handle)
		{
		}




		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			StartGameButton.TouchUpInside += (sender, e) => {

				if (NickTextField.Text != null){
					PerformSegue("JumpToListOfGames", this);
				}
			};
		}
			
	}
}
