// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace rpsls
{
	public partial class CreateNewGameViewController : UIViewController
	{
		public CreateNewGameViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			CreateNewGameButton.TouchUpInside += (sender, e) => {

				if (NewGameName.Text != null){
					PerformSegue("JumpToNewGame", this);
				}
			};

			//View.BackgroundColor = UIColor.FromPatternImage(UIImage.FromFile("Background.jpg"));
		}
	}
}
