// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace rpsls
{
	public partial class OneGameViewController : UIViewController
	{
		public OneGameViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
