// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;

using Foundation;
using UIKit;

namespace rpsls
{
	public partial class OneGameViewController : UIViewController
	{

		UIButton rock;
		UIButton paper;
		UIButton scissor;
		UIButton lizzard;
		UIButton spock;

		public OneGameViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			View.BackgroundColor = UIColor.Black;

			CreateMoveButtons ();
//			CreateConstraints ();
//			SetUpGestures ();

		}

		void CreateMoveButtons ()
		{   
			ApplyViewTo (RockButton,"Rock.png");
			ApplyViewTo (PaperButton, "Paper.png");
			ApplyViewTo (ScissorButton, "Scissor.png");
			ApplyViewTo (LizzardButton, "Lizzard.png");
			ApplyViewTo (SpockButton, "Spock.png");
		}

		void ApplyViewTo (UIButton button, string moveImage)
		{
			button.SetImage(UIImage.FromFile ("Images/" + moveImage), UIControlState.Normal);
			button.Layer.CornerRadius = 15;
		}
			
	}
}
